apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    #Project ID
    app: node-app-160805
spec:
  #Run two instances of our application
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app-160805
    spec:
      #Container details
      containers:
        - name: node-app
          image: gcr.io/node-app-160805/node-app:0.0.1
          imagePullPolicy: Always
          #Ports to expose
          ports:
          - containerPort: 8000